name: Deploy Web App to EC2

on:
  push:
    branches:
      - main  # Trigger on pushing to the 'main' branch added

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t neermor/webapp .
          docker push neermor/webapp

      # SSH into EC2 and deploy the container
      - name: SSH to EC2 and deploy Docker container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Install Docker if not installed
            sudo yum install -y docker
            sudo service docker start
            # Pull the image from DockerHub
            docker pull neermor/webapp
            sudo usermod -aG docker ec2-user  # Add ec2-user to docker group
            newgrp docker  # Apply group changes
            # Run the container on EC2
            docker run -d -p 8080:80 neermor/webapp
